### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by Starnight91** [Arafatulislamantor/YouTubeReVancedUnofficial#1]
Hello.
I try to install it with magisk. All is dine but after reboot, module doesn't appear and youtube was uninstalled.

**Comment by Arafatulislamantor** [comment]
which your device?

**Comment by Arafatulislamantor** [comment]
> Hello. I try to install it with magisk. All is dine but after reboot, module doesn't appear and youtube was uninstalled.

Which your device model?
